version: '3'

services:
  mysql:
    container_name: mysql_container
    image: 'mysql:latest'
    environment:
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - "3306:3306"
    networks:
      - larica
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "8080:8080"
    environment:
        KC_DB: mysql
        DB: mysql
        DB_ADDR: mysql
        DB_URL_HOST: http://localhost:3306
        DB_SCHEMA: keycloak
        DB_USERNAME: kc_user
        DB_PASSWORD: CHANGE_ME
        DB_VENDOR: mysql
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin

    command: start-dev
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - larica
    depends_on:
      - mysql
volumes:
  keycloak_data:
  mysql_data:

networks:
  larica:
