  version: '3'
  services:
    postgres:
      image: postgres:latest
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - local

    keycloak:
      image: quay.io/keycloak/keycloak:24.0.3
      command: start-dev
      restart: always
      links:
        - postgres
      ports:
        - "9081:8080"
      environment:
        KEYCLOAK_IMPORT: /opt/keycloak/import/realm-export.json
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin@1234
        KC_DB: postgres
        KC_DB_SCHEMA: public
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      volumes:
        - keycloak_data:/opt/keycloak/data
      networks:
        - local

  volumes:
    postgres_data:
    keycloak_data:

  networks:
    local:
