spring:
  application:
    name: larica
  datasource:
    url: jdbc:postgresql://localhost:5432/db_restaurante
    username: keycloak
    password: password
    hikari:
      schema: db_restaurante
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: firmas-food
            client-secret: "**********"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:9081/realms/firmas-food-dev
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/firmas-food-dev

server:
  port: 8081

keycloak:
  credentials:
    secret: "**********"
  resource: admin-cli
  auth-server-url:  http://localhost:9081
  realm: firmas-food-dev

