spring:
  application:
    name: larica
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: keycloak
    password: password
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: firmas-food
            client-secret: Ku8D9ZO1Kdkf7NGjiNh2rQu6hLMe7ebJ
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:9081/realms/firmas-food-dev
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/firmas-food-dev

server:
  port: 8081

keycloak:
  credentials:
    secret: aoGHnpGJ9B7zDXyvi2t4PLa52JrIftOu
  resource: admin-cli
  auth-server-url:  http://localhost:9081
  realm: firmas-food-dev

