package danieldjgomes.larica.app.usecase.pedido.enums;

public enum StatusPedido {

    VERIFICANDO_DISPONIBILIDADE,
    PEDIDO_INDISPONIVEL,
    VALIDANDO_PEDIDO,
    PEDIDO_INVALIDO,
    PROCESSANDO_PAGAMENTO,
    FALHA_NO_PAGAMENTO,
    PREPARANDO_PEDIDO,
    PEDIDO_SAIU_PARA_ENTREGA,
    PEDIDO_ENTREGUE,
    FALHA_NA_ENTREGA,
    PEDIDO_FINALIZADO,
    PEDIDO_CANCELADO
}
